/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWeeklyDropRouteImport } from './routes/api/weekly-drop'
import { Route as ApiInsightsRouteImport } from './routes/api/insights'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedProviderRouteImport } from './routes/_authenticated/provider'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedEmployerRouteImport } from './routes/_authenticated/employer'
import { Route as AuthenticatedConciergeRouteImport } from './routes/_authenticated/concierge'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api/public/seed-demo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeeklyDropRoute = ApiWeeklyDropRouteImport.update({
  id: '/api/weekly-drop',
  path: '/api/weekly-drop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProviderRoute = AuthenticatedProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerRoute = AuthenticatedEmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConciergeRoute = AuthenticatedConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/cart': typeof AuthenticatedCartRoute
  '/concierge': typeof AuthenticatedConciergeRoute
  '/employer': typeof AuthenticatedEmployerRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/weekly-drop': typeof ApiWeeklyDropRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/cart': typeof AuthenticatedCartRoute
  '/concierge': typeof AuthenticatedConciergeRoute
  '/employer': typeof AuthenticatedEmployerRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/weekly-drop': typeof ApiWeeklyDropRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/concierge': typeof AuthenticatedConciergeRoute
  '/_authenticated/employer': typeof AuthenticatedEmployerRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/provider': typeof AuthenticatedProviderRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/weekly-drop': typeof ApiWeeklyDropRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/cart'
    | '/concierge'
    | '/employer'
    | '/marketplace'
    | '/provider'
    | '/requests'
    | '/api/chat'
    | '/api/insights'
    | '/api/weekly-drop'
    | '/api/public/seed-demo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/cart'
    | '/concierge'
    | '/employer'
    | '/marketplace'
    | '/provider'
    | '/requests'
    | '/api/chat'
    | '/api/insights'
    | '/api/weekly-drop'
    | '/api/public/seed-demo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/cart'
    | '/_authenticated/concierge'
    | '/_authenticated/employer'
    | '/_authenticated/marketplace'
    | '/_authenticated/provider'
    | '/_authenticated/requests'
    | '/api/chat'
    | '/api/insights'
    | '/api/weekly-drop'
    | '/api/public/seed-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
  ApiWeeklyDropRoute: typeof ApiWeeklyDropRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weekly-drop': {
      id: '/api/weekly-drop'
      path: '/api/weekly-drop'
      fullPath: '/api/weekly-drop'
      preLoaderRoute: typeof ApiWeeklyDropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider': {
      id: '/_authenticated/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof AuthenticatedProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer': {
      id: '/_authenticated/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AuthenticatedEmployerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concierge': {
      id: '/_authenticated/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof AuthenticatedConciergeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedConciergeRoute: typeof AuthenticatedConciergeRoute
  AuthenticatedEmployerRoute: typeof AuthenticatedEmployerRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedProviderRoute: typeof AuthenticatedProviderRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedConciergeRoute: AuthenticatedConciergeRoute,
  AuthenticatedEmployerRoute: AuthenticatedEmployerRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedProviderRoute: AuthenticatedProviderRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiInsightsRoute: ApiInsightsRoute,
  ApiWeeklyDropRoute: ApiWeeklyDropRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
